export {default as HomeView} from './HomeView.vue'
export {default as RegisterView} from './RegisterView.vue'
export {default as LoginView} from './LoginView.vue'
export {default as ArticleDetailView} from './ArticleDetailView.vue'
export {default as CreateArticleView} from './CreateArticleView.vue'
export {default as EditArticleView} from './EditArticleView.vue'
